
[connections.DEV]
account = "fniofia-px03401"
user = "MIHIRPRAJAPATI04"
password = "Mihir@11102004"
database = "STREAMLIT_APP"
schema = "STREAMLIT_APP_POC"
warehouse = "COMPUTE_WH"
role = "SYSADMIN"
